name: Cache Demo

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: prime-cache-285bf39
      id: prime-cache-285bf39
      uses: actions/cache@v4
      with:
        key: cache-285bf39
        path: ~/.cache
        
    - name: Echo cache result
      run: echo "Cache ${{ steps.prime-cache-285bf39.outcome }} for key cache-285bf39"
